apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingress-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: ingress-values
    creationPolicy: Owner
    template:
      data:
        values.yaml: "{{ .conf | fromJson | toYaml }}"
  data:
   - secretKey: conf
     remoteRef:
       key: main
       property: ingress-values.yaml
